local opts = { noremap = true, silent = true }
local map = vim.keymap.set

map('n', '<Esc>', '<cmd>nohlsearch<CR>')
map('t', '<Esc><Esc>', '<C-\\><C-n>')
map('n', '<C-h>', '<C-w><C-h>')
map('n', '<C-l>', '<C-w><C-l>')
map('n', '<C-j>', '<C-w><C-j>')
map('n', '<C-k>', '<C-w><C-k>')
map('n', 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
map('n', 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })
map('n', '<C-Up>', '<cmd>resize +2<cr>')
map('n', '<C-Down>', '<cmd>resize -2<cr>')
map('n', '<C-Left>', '<cmd>vertical resize -2<cr>')
map('n', '<C-Right>', '<cmd>vertical resize +2<cr>')
map('n', '<A-O>', 'O<Esc>')
map('n', '<A-o>', 'o<Esc>')
map('n', '<A-j>', ':m .+1<cr>==')
map('v', '<A-j>', ":m '>+1<cr>gv=gv")
map('i', '<A-j>', '<Esc>:m .+1<cr>==gi')
map('n', '<A-k>', ':m .-2<cr>==')
map('v', '<A-k>', ":m '<-2<cr>gv=gv")
map('i', '<A-k>', '<Esc>:m .-2<cr>==gi')
map('n', '<leader>nb', '<cmd>enew<cr>')
map('n', '<leader>w', '<cmd>w<cr><esc>')
map('n', '<leader>q', ':q!<CR>', opts)
map('n', '<leader>Q', 'qa!<CR>', opts)
map('v', '<', '<gv')
map('v', '>', '>gv')
map('n', 'x', '"_x', { silent = true })
map('n', 'X', ':keeppatterns substitute/\\s*\\%#\\s*/\\r/e <bar> normal! ==^<cr>', { silent = true })
map('n', '<leader>-', '<C-W>v')
map('n', '<leader>|', '<C-W>s')
map('n', '<leader>x', '<C-w>c')
map('n', '<Right>', '<cmd>bprevious<cr>')
map('n', '<Left>', '<cmd>bnext<cr>')
map('n', '<leader>bd', '<cmd>bdelete<cr>')
map('n', '<leader>bb', '<cmd>e #<cr>')
map('n', '<leader>to', ':tabnew<CR>')
map('n', '<leader>tc', ':tabclose<CR>')
map('n', '<leader>tn', ':tabn<CR>')
map('n', '<leader>tp', ':tabp<CR>')
map('i', 'jj', '<ESC>', opts)
map('i', 'jk', '<ESC>', opts)
map({ 'n', 'x', 'o' }, 'H', '^', opts)
map({ 'n', 'x', 'o' }, 'L', '$', opts)
map('n', '<C-a>', 'gg<S-v>G', { silent = true })
map('n', '<leader>es', '<cmd>setlocal spell spelllang=es<cr>')
map('n', '<leader>en', '<cmd>setlocal spell spelllang=en<cr>')

function ToggleRelativeLineNumber()
  vim.wo.relativenumber = not vim.wo.relativenumber
  vim.wo.number = true
end
map('n', '<leader>ct', '<cmd>lua ToggleRelativeLineNumber()<cr>')
